from flask import Flask, request, jsonify
from flask_cors import CORS

print(">>> Flask API başlatılıyor...")  # Terminalde göreceğin test satırı

app = Flask(__name__)
CORS(app)  # Tarayıcıdan gelen isteklere izin ver

# Örnek soru veritabanı
QUESTIONS = {
        "A1": [
    {"q": "Apple ne demek?", "a": "elma"},
    {"q": "Car ne demek?", "a": "araba"},
    {"q": "Blue ne demek?", "a": "mavi"},
    {"q": "Dog ne demek?", "a": "köpek"},
    {"q": "Cat ne demek?", "a": "kedi"},
    {"q": "Book ne demek?", "a": "kitap"},
    {"q": "Pen ne demek?", "a": "kalem"},
    {"q": "House ne demek?", "a": "ev"},
    {"q": "School ne demek?", "a": "okul"},
    {"q": "Chair ne demek?", "a": "sandalye"},
    {"q": "Table ne demek?", "a": "masa"},
    {"q": "Sun ne demek?", "a": "güneş"},
    {"q": "Moon ne demek?", "a": "ay"},
    {"q": "Water ne demek?", "a": "su"},
    {"q": "Milk ne demek?", "a": "süt"},
    {"q": "Bread ne demek?", "a": "ekmek"},
    {"q": "Fish ne demek?", "a": "balık"},
    {"q": "Bird ne demek?", "a": "kuş"},
    {"q": "Flower ne demek?", "a": "çiçek"},
    {"q": "Tree ne demek?", "a": "ağaç"},
    {"q": "Window ne demek?", "a": "pencere"},
    {"q": "Door ne demek?", "a": "kapı"},
    {"q": "Phone ne demek?", "a": "telefon"},
    {"q": "Computer ne demek?", "a": "bilgisayar"},
    {"q": "Bag ne demek?", "a": "çanta"},
    {"q": "Star ne demek?", "a": "yıldız"},
    {"q": "Girl ne demek?", "a": "kız"},
    {"q": "Boy ne demek?", "a": "erkek"},
    {"q": "Mother ne demek?", "a": "anne"},
    {"q": "Father ne demek?", "a": "baba"},
    {"q": "Sister ne demek?", "a": "kız kardeş"},
    {"q": "Brother ne demek?", "a": "erkek kardeş"},
    {"q": "Baby ne demek?", "a": "bebek"},
    {"q": "City ne demek?", "a": "şehir"},
    {"q": "Country ne demek?", "a": "ülke"},
    {"q": "Street ne demek?", "a": "sokak"},
    {"q": "Road ne demek?", "a": "yol"},
    {"q": "Food ne demek?", "a": "yemek"},
    {"q": "Tea ne demek?", "a": "çay"},
    {"q": "Coffee ne demek?", "a": "kahve"},
    {"q": "Sugar ne demek?", "a": "şeker"},
    {"q": "Salt ne demek?", "a": "tuz"},
    {"q": "Egg ne demek?", "a": "yumurta"},
    {"q": "Meat ne demek?", "a": "et"},
    {"q": "Rice ne demek?", "a": "pirinç"},
    {"q": "Soup ne demek?", "a": "çorba"},
    {"q": "Happy ne demek?", "a": "mutlu"},
    {"q": "Sad ne demek?", "a": "üzgün"},
    {"q": "Big ne demek?", "a": "büyük"},
    {"q": "Small ne demek?", "a": "küçük"},
    {"q": "Hot ne demek?", "a": "sıcak"},
    {"q": "Cold ne demek?", "a": "soğuk"},
    {"q": "Fast ne demek?", "a": "hızlı"},
    {"q": "Slow ne demek?", "a": "yavaş"},
    {"q": "Easy ne demek?", "a": "kolay"},
    {"q": "Hard ne demek?", "a": "zor"},
    {"q": "Good ne demek?", "a": "iyi"},
    {"q": "Bad ne demek?", "a": "kötü"},
    {"q": "Young ne demek?", "a": "genç"},
    {"q": "Old ne demek?", "a": "yaşlı"},
    {"q": "New ne demek?", "a": "yeni"},
    {"q": "Long ne demek?", "a": "uzun"},
    {"q": "Short ne demek?", "a": "kısa"},
    {"q": "Friend ne demek?", "a": "arkadaş"},
    {"q": "Family ne demek?", "a": "aile"},
    {"q": "Work ne demek?", "a": "iş"},
    {"q": "Job ne demek?", "a": "meslek"},
    {"q": "Teacher ne demek?", "a": "öğretmen"},
    {"q": "Student ne demek?", "a": "öğrenci"},
    {"q": "Doctor ne demek?", "a": "doktor"},
    {"q": "Nurse ne demek?", "a": "hemşire"},
    {"q": "Police ne demek?", "a": "polis"},
    {"q": "Fire ne demek?", "a": "ateş"},
    {"q": "Rain ne demek?", "a": "yağmur"},
    {"q": "Snow ne demek?", "a": "kar"},
    {"q": "Wind ne demek?", "a": "rüzgar"},
    {"q": "Sea ne demek?", "a": "deniz"},
    {"q": "Lake ne demek?", "a": "göl"},
    {"q": "Mountain ne demek?", "a": "dağ"},
    {"q": "River ne demek?", "a": "nehir"},
    {"q": "Music ne demek?", "a": "müzik"},
    {"q": "Movie ne demek?", "a": "film"},
    {"q": "Game ne demek?", "a": "oyun"},
    {"q": "Phone ne demek?", "a": "telefon"},
    {"q": "Clock ne demek?", "a": "saat"},
    {"q": "Light ne demek?", "a": "ışık"},
    {"q": "Dark ne demek?", "a": "karanlık"},
    {"q": "Room ne demek?", "a": "oda"},
    {"q": "Kitchen ne demek?", "a": "mutfak"},
    {"q": "Bathroom ne demek?", "a": "banyo"},
    {"q": "Garden ne demek?", "a": "bahçe"},
    {"q": "Clothes ne demek?", "a": "kıyafet"},
    {"q": "Shoes ne demek?", "a": "ayakkabı"},
    {"q": "T-shirt ne demek?", "a": "tişört"},
    {"q": "Pants ne demek?", "a": "pantolon"},
    {"q": "Hat ne demek?", "a": "şapka"},
    {"q": "Train ne demek?", "a": "tren"},
    {"q": "Bus ne demek?", "a": "otobüs"},
    {"q": "Bike ne demek?", "a": "bisiklet"},
    {"q": "Airport ne demek?", "a": "havaalanı"} 
    ],

    "A2": [
    {"q": "Agree ne demek?", "a": "katılmak"},
    {"q": "Arrive ne demek?", "a": "varmak"},
    {"q": "Believe ne demek?", "a": "inanmak"},
    {"q": "Borrow ne demek?", "a": "ödünç almak"},
    {"q": "Choose ne demek?", "a": "seçmek"},
    {"q": "Clean ne demek?", "a": "temizlemek"},
    {"q": "Climb ne demek?", "a": "tırmanmak"},
    {"q": "Close ne demek?", "a": "kapatmak"},
    {"q": "Collect ne demek?", "a": "toplamak"},
    {"q": "Complain ne demek?", "a": "şikayet etmek"},
    {"q": "Continue ne demek?", "a": "devam etmek"},
    {"q": "Cough ne demek?", "a": "öksürmek"},
    {"q": "Cover ne demek?", "a": "örtmek"},
    {"q": "Cry ne demek?", "a": "ağlamak"},
    {"q": "Decide ne demek?", "a": "karar vermek"},
    {"q": "Deliver ne demek?", "a": "teslim etmek"},
    {"q": "Describe ne demek?", "a": "tanımlamak"},
    {"q": "Destroy ne demek?", "a": "yok etmek"},
    {"q": "Develop ne demek?", "a": "geliştirmek"},
    {"q": "Discover ne demek?", "a": "keşfetmek"},
    {"q": "Divide ne demek?", "a": "bölmek"},
    {"q": "Dress ne demek?", "a": "giyinmek"},
    {"q": "Drop ne demek?", "a": "düşürmek"},
    {"q": "Earn ne demek?", "a": "kazanmak"},
    {"q": "Explain ne demek?", "a": "açıklamak"},
    {"q": "Feed ne demek?", "a": "beslemek"},
    {"q": "Fill ne demek?", "a": "doldurmak"},
    {"q": "Follow ne demek?", "a": "takip etmek"},
    {"q": "Guess ne demek?", "a": "tahmin etmek"},
    {"q": "Hate ne demek?", "a": "nefret etmek"},
    {"q": "Help ne demek?", "a": "yardım etmek"},
    {"q": "Hope ne demek?", "a": "umut etmek"},
    {"q": "Hurry ne demek?", "a": "acele etmek"},
    {"q": "Invite ne demek?", "a": "davet etmek"},
    {"q": "Join ne demek?", "a": "katılmak"},
    {"q": "Jump ne demek?", "a": "zıplamak"},
    {"q": "Laugh ne demek?", "a": "gülmek"},
    {"q": "Learn ne demek?", "a": "öğrenmek"},
    {"q": "Lie ne demek?", "a": "yalan söylemek"},
    {"q": "Listen ne demek?", "a": "dinlemek"},
    {"q": "Lose ne demek?", "a": "kaybetmek"},
    {"q": "Move ne demek?", "a": "hareket etmek"},
    {"q": "Offer ne demek?", "a": "teklif etmek"},
    {"q": "Open ne demek?", "a": "açmak"},
    {"q": "Order ne demek?", "a": "sipariş etmek"},
    {"q": "Paint ne demek?", "a": "boyamak"},
    {"q": "Pass ne demek?", "a": "geçmek"},
    {"q": "Pick ne demek?", "a": "toplamak"},
    {"q": "Plan ne demek?", "a": "planlamak"},
    {"q": "Practice ne demek?", "a": "pratik yapmak"},
    {"q": "Prefer ne demek?", "a": "tercih etmek"},
    {"q": "Prepare ne demek?", "a": "hazırlamak"},
    {"q": "Protect ne demek?", "a": "korumak"},
    {"q": "Reach ne demek?", "a": "ulaşmak"},
    {"q": "Relax ne demek?", "a": "rahatlamak"},
    {"q": "Remember ne demek?", "a": "hatırlamak"},
    {"q": "Repair ne demek?", "a": "tamir etmek"},
    {"q": "Repeat ne demek?", "a": "tekrar etmek"},
    {"q": "Return ne demek?", "a": "geri dönmek"},
    {"q": "Save ne demek?", "a": "kaydetmek"},
    {"q": "Send ne demek?", "a": "göndermek"},
    {"q": "Share ne demek?", "a": "paylaşmak"},
    {"q": "Shout ne demek?", "a": "bağırmak"},
    {"q": "Smile ne demek?", "a": "gülümsemek"},
    {"q": "Spend ne demek?", "a": "harcamak"},
    {"q": "Stand ne demek?", "a": "ayakta durmak"},
    {"q": "Start ne demek?", "a": "başlamak"},
    {"q": "Stay ne demek?", "a": "kalmak"},
    {"q": "Stop ne demek?", "a": "durmak"},
    {"q": "Suggest ne demek?", "a": "önermek"},
    {"q": "Talk ne demek?", "a": "konuşmak"},
    {"q": "Teach ne demek?", "a": "öğretmek"},
    {"q": "Turn ne demek?", "a": "dönmek"},
    {"q": "Travel ne demek?", "a": "seyahat etmek"},
    {"q": "Try ne demek?", "a": "denemek"},
    {"q": "Visit ne demek?", "a": "ziyaret etmek"},
    {"q": "Wait ne demek?", "a": "beklemek"},
    {"q": "Walk ne demek?", "a": "yürümek"},
    {"q": "Want ne demek?", "a": "istemek"},
    {"q": "Warm ne demek?", "a": "ılık"},
    {"q": "Wash ne demek?", "a": "yıkamak"},
    {"q": "Watch ne demek?", "a": "izlemek"},
    {"q": "Wish ne demek?", "a": "dilemek"},
    {"q": "Work ne demek?", "a": "çalışmak"},
    {"q": "Write ne demek?", "a": "yazmak"},
    {"q": "Answer ne demek?", "a": "cevaplamak"},
    {"q": "Arrive ne demek?", "a": "varmak"},
    {"q": "Carry ne demek?", "a": "taşımak"},
    {"q": "Count ne demek?", "a": "saymak"},
    {"q": "Fix ne demek?", "a": "tamir etmek"},
    {"q": "Guess ne demek?", "a": "tahmin etmek"},
    {"q": "Improve ne demek?", "a": "geliştirmek"},
    {"q": "Promise ne demek?", "a": "söz vermek"}
    ],
    "B1": [
    {"q": "Achieve ne demek?", "a": "başarmak"},
    {"q": "Allow ne demek?", "a": "izin vermek"},
    {"q": "Announce ne demek?", "a": "duyurmak"},
    {"q": "Approach ne demek?", "a": "yaklaşmak"},
    {"q": "Argue ne demek?", "a": "tartışmak"},
    {"q": "Arrange ne demek?", "a": "düzenlemek"},
    {"q": "Attend ne demek?", "a": "katılmak"},
    {"q": "Avoid ne demek?", "a": "kaçınmak"},
    {"q": "Balance ne demek?", "a": "dengelemek"},
    {"q": "Behave ne demek?", "a": "davranmak"},
    {"q": "Blame ne demek?", "a": "suçlamak"},
    {"q": "Cause ne demek?", "a": "sebep olmak"},
    {"q": "Compare ne demek?", "a": "karşılaştırmak"},
    {"q": "Complain ne demek?", "a": "şikayet etmek"},
    {"q": "Confirm ne demek?", "a": "onaylamak"},
    {"q": "Connect ne demek?", "a": "bağlamak"},
    {"q": "Consider ne demek?", "a": "düşünmek"},
    {"q": "Convince ne demek?", "a": "ikna etmek"},
    {"q": "Create ne demek?", "a": "oluşturmak"},
    {"q": "Decrease ne demek?", "a": "azaltmak"},
    {"q": "Deliver ne demek?", "a": "teslim etmek"},
    {"q": "Demand ne demek?", "a": "talep etmek"},
    {"q": "Describe ne demek?", "a": "tanımlamak"},
    {"q": "Develop ne demek?", "a": "geliştirmek"},
    {"q": "Divide ne demek?", "a": "bölmek"},
    {"q": "Encourage ne demek?", "a": "cesaretlendirmek"},
    {"q": "Establish ne demek?", "a": "kurmak"},
    {"q": "Estimate ne demek?", "a": "tahmin etmek"},
    {"q": "Examine ne demek?", "a": "incelemek"},
    {"q": "Experience ne demek?", "a": "deneyimlemek"},
    {"q": "Express ne demek?", "a": "ifade etmek"},
    {"q": "Handle ne demek?", "a": "idare etmek"},
    {"q": "Identify ne demek?", "a": "tanımlamak"},
    {"q": "Increase ne demek?", "a": "artırmak"},
    {"q": "Include ne demek?", "a": "içermek"},
    {"q": "Influence ne demek?", "a": "etkilemek"},
    {"q": "Inform ne demek?", "a": "bilgilendirmek"},
    {"q": "Insist ne demek?", "a": "ısrar etmek"},
    {"q": "Intend ne demek?", "a": "niyet etmek"},
    {"q": "Interview ne demek?", "a": "röportaj yapmak"},
    {"q": "Introduce ne demek?", "a": "tanıtmak"},
    {"q": "Manage ne demek?", "a": "yönetmek"},
    {"q": "Measure ne demek?", "a": "ölçmek"},
    {"q": "Notice ne demek?", "a": "fark etmek"},
    {"q": "Offer ne demek?", "a": "teklif etmek"},
    {"q": "Organize ne demek?", "a": "organize etmek"},
    {"q": "Participate ne demek?", "a": "katılmak"},
    {"q": "Perform ne demek?", "a": "sergilemek"},
    {"q": "Predict ne demek?", "a": "tahmin etmek"},
    {"q": "Prevent ne demek?", "a": "engellemek"},
    {"q": "Produce ne demek?", "a": "üretmek"},
    {"q": "Promise ne demek?", "a": "söz vermek"},
    {"q": "Publish ne demek?", "a": "yayınlamak"},
    {"q": "Realize ne demek?", "a": "fark etmek"},
    {"q": "Recommend ne demek?", "a": "tavsiye etmek"},
    {"q": "Reduce ne demek?", "a": "azaltmak"},
    {"q": "Refuse ne demek?", "a": "reddetmek"},
    {"q": "Release ne demek?", "a": "serbest bırakmak"},
    {"q": "Replace ne demek?", "a": "yerini değiştirmek"},
    {"q": "Require ne demek?", "a": "gerektirmek"},
    {"q": "Respect ne demek?", "a": "saygı duymak"},
    {"q": "Review ne demek?", "a": "gözden geçirmek"},
    {"q": "Select ne demek?", "a": "seçmek"},
    {"q": "Share ne demek?", "a": "paylaşmak"},
    {"q": "Solve ne demek?", "a": "çözmek"},
    {"q": "Suggest ne demek?", "a": "önermek"},
    {"q": "Support ne demek?", "a": "desteklemek"},
    {"q": "Train ne demek?", "a": "eğitmek"},
    {"q": "Translate ne demek?", "a": "çeviri yapmak"},
    {"q": "Warn ne demek?", "a": "uyarmak"},
    {"q": "Wonder ne demek?", "a": "merak etmek"},
    {"q": "Accept ne demek?", "a": "kabul etmek"},
    {"q": "Achieve ne demek?", "a": "başarmak"},
    {"q": "Appreciate ne demek?", "a": "takdir etmek"},
    {"q": "Assist ne demek?", "a": "yardım etmek"},
    {"q": "Attend ne demek?", "a": "katılmak"},
    {"q": "Balance ne demek?", "a": "dengelemek"},
    {"q": "Behave ne demek?", "a": "davranmak"},
    {"q": "Celebrate ne demek?", "a": "kutlamak"},
    {"q": "Compare ne demek?", "a": "karşılaştırmak"},
    {"q": "Deliver ne demek?", "a": "teslim etmek"},
    {"q": "Encourage ne demek?", "a": "cesaretlendirmek"},
    {"q": "Experience ne demek?", "a": "deneyim"},
    {"q": "Intend ne demek?", "a": "niyet etmek"},
    {"q": "Manage ne demek?", "a": "idare etmek"},
    {"q": "Observe ne demek?", "a": "gözlemlemek"},
    {"q": "Protect ne demek?", "a": "korumak"},
    {"q": "Recognize ne demek?", "a": "tanımak"},
    {"q": "Rush ne demek?", "a": "acele etmek"},
    {"q": "Suffer ne demek?", "a": "acı çekmek"},
    {"q": "Survive ne demek?", "a": "hayatta kalmak"},
    {"q": "Warn ne demek?", "a": "uyarmak"}
],

    "B2": [
    {"q": "Acquire ne demek?", "a": "edinmek"},
    {"q": "Adjust ne demek?", "a": "ayarlamak"},
    {"q": "Administer ne demek?", "a": "yönetmek"},
    {"q": "Alter ne demek?", "a": "değiştirmek"},
    {"q": "Anticipate ne demek?", "a": "beklemek"},
    {"q": "Assess ne demek?", "a": "değerlendirmek"},
    {"q": "Assume ne demek?", "a": "varsaymak"},
    {"q": "Attempt ne demek?", "a": "denemek"},
    {"q": "Authorize ne demek?", "a": "yetkilendirmek"},
    {"q": "Clarify ne demek?", "a": "açıklığa kavuşturmak"},
    {"q": "Collaborate ne demek?", "a": "işbirliği yapmak"},
    {"q": "Commit ne demek?", "a": "adamak"},
    {"q": "Compete ne demek?", "a": "rekabet etmek"},
    {"q": "Comprehend ne demek?", "a": "kavramak"},
    {"q": "Conclude ne demek?", "a": "sonuçlandırmak"},
    {"q": "Conduct ne demek?", "a": "yürütmek"},
    {"q": "Contribute ne demek?", "a": "katkıda bulunmak"},
    {"q": "Convert ne demek?", "a": "dönüştürmek"},
    {"q": "Declare ne demek?", "a": "ilan etmek"},
    {"q": "Demonstrate ne demek?", "a": "göstermek"},
    {"q": "Determine ne demek?", "a": "belirlemek"},
    {"q": "Differentiate ne demek?", "a": "ayırt etmek"},
    {"q": "Eliminate ne demek?", "a": "elemek"},
    {"q": "Emphasize ne demek?", "a": "vurgulamak"},
    {"q": "Ensure ne demek?", "a": "sağlamak"},
    {"q": "Establish ne demek?", "a": "kurmak"},
    {"q": "Evaluate ne demek?", "a": "değerlendirmek"},
    {"q": "Expand ne demek?", "a": "genişletmek"},
    {"q": "Facilitate ne demek?", "a": "kolaylaştırmak"},
    {"q": "Forecast ne demek?", "a": "tahmin etmek"},
    {"q": "Guarantee ne demek?", "a": "garanti etmek"},
    {"q": "Generate ne demek?", "a": "oluşturmak"},
    {"q": "Implement ne demek?", "a": "uygulamak"},
    {"q": "Imply ne demek?", "a": "ima etmek"},
    {"q": "Indicate ne demek?", "a": "belirtmek"},
    {"q": "Influence ne demek?", "a": "etkilemek"},
    {"q": "Interpret ne demek?", "a": "yorumlamak"},
    {"q": "Justify ne demek?", "a": "haklı çıkarmak"},
    {"q": "Maintain ne demek?", "a": "sürdürmek"},
    {"q": "Negotiate ne demek?", "a": "müzakere etmek"},
    {"q": "Obtain ne demek?", "a": "elde etmek"},
    {"q": "Overcome ne demek?", "a": "üstesinden gelmek"},
    {"q": "Persuade ne demek?", "a": "ikna etmek"},
    {"q": "Predict ne demek?", "a": "öngörmek"},
    {"q": "Preserve ne demek?", "a": "korumak"},
    {"q": "Prevent ne demek?", "a": "engellemek"},
    {"q": "Propose ne demek?", "a": "önermek"},
    {"q": "Pursue ne demek?", "a": "peşinden koşmak"},
    {"q": "Require ne demek?", "a": "gerektirmek"},
    {"q": "Restore ne demek?", "a": "yenilemek"},
    {"q": "Reveal ne demek?", "a": "ortaya çıkarmak"},
    {"q": "Sustain ne demek?", "a": "devam ettirmek"},
    {"q": "Strengthen ne demek?", "a": "güçlendirmek"},
    {"q": "Specify ne demek?", "a": "belirtmek"},
    {"q": "Summarize ne demek?", "a": "özetlemek"},
    {"q": "Transform ne demek?", "a": "dönüştürmek"},
    {"q": "Verify ne demek?", "a": "doğrulamak"},
    {"q": "Address ne demek?", "a": "hitap etmek"},
    {"q": "Acknowledge ne demek?", "a": "kabul etmek"},
    {"q": "Adapt ne demek?", "a": "uyum sağlamak"},
    {"q": "Administer ne demek?", "a": "yönetmek"},
    {"q": "Allocate ne demek?", "a": "tahsis etmek"},
    {"q": "Analyze ne demek?", "a": "analiz etmek"},
    {"q": "Anticipate ne demek?", "a": "beklemek"},
    {"q": "Clarify ne demek?", "a": "açıklığa kavuşturmak"},
    {"q": "Compile ne demek?", "a": "derlemek"},
    {"q": "Confront ne demek?", "a": "yüzleşmek"},
    {"q": "Dominate ne demek?", "a": "hakim olmak"},
    {"q": "Enable ne demek?", "a": "mümkün kılmak"},
    {"q": "Enforce ne demek?", "a": "uygulamak"},
    {"q": "Enhance ne demek?", "a": "arttırmak"},
    {"q": "Exceed ne demek?", "a": "aşmak"},
    {"q": "Formulate ne demek?", "a": "formüle etmek"},
    {"q": "Illustrate ne demek?", "a": "örneklemek"},
    {"q": "Modify ne demek?", "a": "değiştirmek"},
    {"q": "Monitor ne demek?", "a": "izlemek"},
    {"q": "Optimize ne demek?", "a": "optimize etmek"},
    {"q": "Perceive ne demek?", "a": "algılamak"},
    {"q": "Reinforce ne demek?", "a": "pekiştirmek"},
    {"q": "Specify ne demek?", "a": "belirtmek"},
    {"q": "Stimulate ne demek?", "a": "uyarmak"},
    {"q": "Target ne demek?", "a": "hedef almak"},
    {"q": "Undertake ne demek?", "a": "üstlenmek"},
    {"q": "Utilize ne demek?", "a": "kullanmak"},
    {"q": "Vary ne demek?", "a": "değişiklik göstermek"},
    {"q": "Witness ne demek?", "a": "tanık olmak"},
    {"q": "Widen ne demek?", "a": "genişletmek"}
]

}


@app.get("/api/questions")
def get_questions():
    level = request.args.get("level", "A1")
    return jsonify(QUESTIONS.get(level, []))


if __name__ == "__main__":
    app.run(debug=True)
